package masSim.schedule;

public enum SchedulingCommandType {
	CALCULATECOST,
	COSTBROADCAST,
	ASSIGNTASK,
	NEGOTIATE,
	DISPLAYADDMETHOD,
	DISPLAYREMOVEMETHOD,
	DISPLAYADDAGENT,
	DISPLAYTASKEXECUTION,
	METHODCOMPLETED,
	TASKCOMPLETED,
	SHUTDOWN,
	INITMSG
}
