package masSim.schedule;

public enum SchedulingCommandType {
	CALCULATECOST,
	PUBLISHCOST,
	ASSIGNTASK,
	NEGOTIATE,
	DISPLAYADDMETHOD,
	DISPLAYREMOVEMETHOD,
	DISPLAYADDAGENT,
	DISPLAYTASKEXECUTION,
	METHODCOMPLETED
}
